### PR TITLE
Update report

### PR DESCRIPTION
**Pull request by mhalagan-nmdp**
- Put all html subroutines in html.pm
- Added testing files for t/report.t
- Added html dom tests for regression testing with t/report.t
- Modified the README
- Added the filter option 
- Added the download option
- Add the ability to use blastn results in the subject pages
- Cleaned up the code
- Removed javascript files that weren't needed and imported several from the web instead of from flat files.

### CODE REVIEW

**Comment by mheuer-nmdp** [comment]
Some of the file diffs are too large for line by line comments.

This needs to be a parameter or configuration option:
```perl
my $url = "http://emmes-dev.nmdp.org:8080/ac/api/decode?typing=$loc*$typ";
```
https://github.com/mhalagan-nmdp/pipeline/blob/b724fac48289a9c20916348e0c48c39e7856916c/validation/ngs-validation-report#L1057

This copyright statement is not compatible with our license
```html
<a href="http://bioinformatics.nmdp.org/Copyright_Information.aspx">Copyright ©</a> 2006 - 2014 National...
```
https://github.com/mhalagan-nmdp/pipeline/blob/b724fac48289a9c20916348e0c48c39e7856916c/validation/lib/html.pm#L1331
(and several other places)

**Comment by mheuer-nmdp** [comment]
I just noticed that the commits in this pull request are from user @mhalagan and not @mhalagan-nmdp who opened up the pull request.  With that and the commits to files outside of the validation directory, maybe these commits should be squashed or another new pull request be created?

**Comment by mhalagan-nmdp** [comment]
The copy right statement it's linked too or the 2006 - 2014 part??

          <p><a href="http://bioinformatics.nmdp.org/Copyright_Information.aspx">Copyright ©</a> 2006 - 2014 National Marrow Donor Program. All Rights Reserved.</p>

Could it be changed to something like this:

          <p><a href="https://github.com/nmdp-bioinformatics/pipeline/blob/master/LICENSE">Copyright ©</a> 2014 - 2015 National Marrow Donor Program. All Rights Reserved.</p>



________________________________

**Comment by mhalagan-nmdp** [comment]
"I just noticed that the commits in this pull request are from user @mhalagan and not @mhalagan-nmdp who opened up the pull request. With that and the commits to files outside of the validation directory, maybe these commits should be squashed or another new pull request be created?"

My git config user.email was set to mhalagan09@gmail.com (mhalagan on github), so I just changed it to mhalagan@nmdp.org.

**Pull request closed without merging**
